/**
 * convoy-contracts.d.ts — remnant-ux-0329
 * Shared TypeScript types for The Remnant UX & Gameplay Overhaul convoy.
 * Generated by Mayor pre-flight on 2026-03-29.
 * FROZEN — do not edit. File AMENDMENT.md in ~/.claude/convoy/remnant-ux-0329/ instead.
 */

// ---------------------------------------------------------------------------
// C2 — Item Stacking (Rider D: lib/inventory.ts)
// ---------------------------------------------------------------------------

export interface GroupedItem {
  itemId: string
  /** Raw item name from item data */
  name: string
  /** Number of this item in the collection */
  count: number
  /** Pre-formatted display string: "Bandages x3" or "Bandages" (count === 1) */
  displayName: string
}

/** Default formatter: returns "Name xN" for count > 1, "Name" for count === 1 */
export type StackFormatter = (name: string, count: number) => string

// ---------------------------------------------------------------------------
// C3 — Vendor Dialogue (Rider C: types/game.ts NPC extension)
// ---------------------------------------------------------------------------

/**
 * Optional vendor personality fields added to the NPC interface.
 * Only set on NPCs that have a tradeInventory.
 */
export interface VendorFields {
  /** Message shown when player opens trade with this NPC */
  vendorGreeting?: string
  /** Message shown when trade session ends */
  vendorFarewell?: string
  /** NPC's .22LR budget (rounds available to spend). If absent, do not display. */
  vendorBudget?: number
  /**
   * Item-specific reaction pool. Key is itemId.
   * On successful sell, roll a random entry from the matching array.
   * If no entry for this itemId, no comment fires.
   */
  vendorComments?: Record<string, string[]>
}

// ---------------------------------------------------------------------------
// C3 — Vendor Dialogue Module (Rider C: lib/actions/vendorDialogue.ts)
// ---------------------------------------------------------------------------

import type { NPC } from './types/game'
import type { GameMessage } from './types/game'

/**
 * Dispatch vendor greeting. Call at the start of handleTrade().
 * Returns undefined if NPC has no vendorGreeting.
 */
export declare function dispatchVendorGreeting(npc: NPC): GameMessage | undefined

/**
 * Dispatch vendor farewell. Call when trade session closes.
 * Returns undefined if NPC has no vendorFarewell.
 */
export declare function dispatchVendorFarewell(npc: NPC): GameMessage | undefined

/**
 * Dispatch vendor budget line. Call after wares listing in handleTrade().
 * Format: "Vendor's budget: {N} rounds"
 * Returns undefined if NPC has no vendorBudget.
 */
export declare function dispatchVendorBudget(npc: NPC): GameMessage | undefined

/**
 * Roll and dispatch a vendor comment for the given itemId.
 * Call after a successful sell transaction.
 * Returns undefined if NPC has no vendorComments for this itemId.
 */
export declare function dispatchVendorComment(npc: NPC, itemId: string): GameMessage | undefined

// ---------------------------------------------------------------------------
// C4 — Commands Tab (Rider G: components/tabs/CommandsTab.tsx)
// ---------------------------------------------------------------------------

export interface CommandEntry {
  /** Display syntax, e.g. "north / n" */
  syntax: string
  /** One-line description, max 60 characters */
  description: string
  /** Additional aliases not shown in syntax field */
  aliases?: string[]
}

export interface CommandCategory {
  /** Category label: "Movement" | "Inventory" | "Social" | "Combat" | "World" | "System" */
  label: string
  commands: CommandEntry[]
}

// ---------------------------------------------------------------------------
// C4 — TAB_IDS with CMD (Rider G: components/PipBoyFrame.tsx)
// ---------------------------------------------------------------------------

/**
 * Updated TAB_IDS after Rider G's change:
 * export const TAB_IDS = ['TERM', 'STAT', 'INV', 'MAP', 'DATA', 'CMD'] as const
 * export type TabId = (typeof TAB_IDS)[number]
 * 'CMD' is added as the last tab.
 */
export type ConvoyTabId = 'TERM' | 'STAT' | 'INV' | 'MAP' | 'DATA' | 'CMD'

// ---------------------------------------------------------------------------
// C1 — Color Palette Reference (Rider A: richText.ts, Terminal.tsx, etc.)
// Reference only — not enforced by TypeScript. See CONTRACT.md C1 for full table.
// ---------------------------------------------------------------------------

/**
 * Canonical 1988 ANSI palette mappings.
 * Used by Rider A. Referenced by all other Riders when adding colored text.
 *
 * richText tags:
 *   item:      text-amber-500
 *   npc:       text-amber-700
 *   enemy:     text-red-700
 *   exit:      text-amber-600
 *   keyword:   text-amber-500
 *   currency:  text-amber-600
 *   condition: text-orange-600
 *   trait:     text-amber-600
 *
 * Terminal message types:
 *   narrative: text-amber-400  (unchanged)
 *   combat:    text-red-700
 *   system:    text-amber-300
 *   error:     text-red-600
 *   echo:      text-amber-700
 */
export type ConvoyColorPalette = never  // marker type — see CONTRACT.md C1 for values
